# H5000M 2.4GHz AP
interface=ap24
driver=nl80211
ssid=H5000M-2.4G
country_code=CN
hw_mode=g
channel=6
ieee80211d=1

# 11n / 11ax（2.4G 保持 20MHz：频段拥挤，40MHz 往往更差）
ieee80211n=1
ieee80211ax=1

wmm_enabled=1
auth_algs=1
ht_capab=[SHORT-GI-20][DSSS_CCK-40]
